using JuMP
using HiGHS
model = Model(HiGHS.Optimizer)

@variable(model, u1)
@variable(model, u2)
@variable(model, x1)
@variable(model, x2)
@objective(model, Min, u1 + 3u2)
@constraint(model, c1, x1 + 2x2 >= 10)
@constraint(model, c2, x1 - x2 == 5)
@constraint(model, c3, x1 <= u1)
@constraint(model, c4, x1 >= -u1)
@constraint(model, c5, x2 <= u2)
@constraint(model, c6, x2 >= -u2)
print(model)
optimize!(model)
@show termination_status(model)
@show primal_status(model)
@show objective_value(model)
@show value(u1)
@show value(u2)
@show value(x1)
@show value(x2)
