rest:
  url: "https://example.org/primenumbers/v1"
  port: 8443

my_string: foo bar


gridsize_range: [4, 5, 6]
t_and_o_probs_range: [1.0, 0.8, 0.6]
z_val_range: [0.7, 0.6, 0.5]

timesteps_range: [1, 2, 3, 4, 5, 6]